org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.200
neoforge_version_range=[21,)
loader_version_range=[21,)
parchment_minecraft=1.21.1
parchment_version=2024.11.17
mantle_version=1.12.DEV.*
tic_version=3.12.0.DEV.*

irons_spells_version=1.21-3.21.0.2
irons_lib_version=1.21-1.0.7

curios_version=5.14.1+1.20.1
geckolib_version=1.20.1:4.8.2
jei_version=19.21.0.247
player_animator_version=1.0.2-rc1+1.20

tconstruct_range=[3.12.0,3.13.0)
irons_spells_range=[1.21-3.21.0,1.21-4.0)

mod_id=constructs_casting
mod_name=Construct's Casting
mod_license=All-Rights-Reserved
mod_version=2.2.5
mod_group_id=com.snackpirate
mod_authors=SnackPirate
mod_description=Bridge between Tinkers' Construct and Iron's Spells 'n Spellbooks.
